In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns 


In [2]:
df= pd.read_csv('D:\Python\ML Live\Modular1\ML_Live-\data\Advertising.csv', index_col=0)
df

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [3]:
X = df.drop('Sales', axis = 1)
X

TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [4]:
y = df['Sales']
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: Sales, Length: 200, dtype: float64

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [6]:
poly_conv = PolynomialFeatures(degree= 3 , include_bias= False)   

In [7]:
final_model = LinearRegression()

In [8]:
poly_features = poly_conv.fit_transform(X)
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [9]:
X.to_numpy()[0]


array([230.1,  37.8,  69.2])

In [10]:
X.shape

(200, 3)

In [11]:
poly_features.shape

(200, 19)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.33, random_state=101)


In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaled_X_train = scaler.fit_transform(X_train)

In [16]:
#scaled_X_train = scaler.transform(X_train)   

In [17]:
scaled_X_test = scaler.fit_transform(X_test)

In [18]:
X_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [19]:
scaled_X_train[0]

array([ 0.455913  , -0.15469995, -0.98899258,  0.23144458,  0.12990319,
       -0.57856073, -0.43655678, -0.66806654, -0.71668198,  0.02389419,
        0.04869878, -0.45436665, -0.22089285, -0.47664217, -0.51504813,
       -0.55818067, -0.60618091, -0.56426029, -0.5063835 ])

In [20]:
scaled_X_test[0]

array([-0.7673027 ,  1.72055304,  0.60170798, -0.86610197,  0.08617854,
       -0.24345669,  2.17200183,  1.32229547,  0.26020656, -0.81234181,
       -0.44688596, -0.53851595,  0.41034572,  0.18272038, -0.20474864,
        2.50807179,  1.72284854,  0.66605881,  0.00620318])

In [29]:
final_model.fit(scaled_X_train, y_train)

LinearRegression()

In [30]:
test_pred_scaled = final_model.predict(scaled_X_test)
test_pred_scaled

array([14.84826074, 19.00816089, 13.14090733, 17.26346112,  8.75048832,
        7.84262177, 19.88173085, 17.25352253, 11.20868175, 19.59376214,
       10.18080447, 14.40838981, 12.33793599, 22.46480864, 18.92021104,
       10.22366019, 13.0965617 , 10.33190532,  9.66306255, 20.99157685,
        7.85738291, 19.12880238, 26.6546466 , 23.94111753, 10.34911367,
       12.03375729, 20.59270512, 10.42302506, 13.12092258,  9.26254226,
        9.59780512, 19.64863977, 11.67760822,  7.90447242, 18.05824535,
       10.328059  , 11.46564387, 10.78830197,  8.01264857, 11.53543802,
       12.83750856, 11.15810028, 12.21544685,  8.53226035, 12.49370351,
       11.47584844,  6.2891926 , 15.71030826, 13.53508757, 21.94946775,
       11.33839131, 13.39466623, 15.46795777, 12.85871946, 11.89979485,
        6.0920417 , 24.2787695 , 10.25921506, 17.42193491, 15.81064129,
       15.42922015, 25.64710405,  9.70512583, 20.91741192, 12.7385853 ,
       21.73568684])

In [31]:
y_test

38     14.7
110    19.8
32     11.9
90     16.7
67      9.5
       ... 
184    26.2
128     8.8
54     21.2
101    11.7
94     22.2
Name: Sales, Length: 66, dtype: float64

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [33]:
mean_squared_error(y_test,test_pred_scaled)

0.7582607646533377

In [34]:
mean_absolute_error(y_test,test_pred_scaled)

0.7170176121709401

In [35]:
np.sqrt(mean_squared_error(y_test,test_pred_scaled))

0.8707816974726431

# Ridge

In [36]:
from sklearn.linear_model import Ridge

In [37]:
ridge_model = Ridge(alpha = 10)

In [38]:
ridge_model.fit(scaled_X_train, y_train)

Ridge(alpha=10)

In [39]:
test_predictions_ridge = ridge_model.predict(scaled_X_test)

In [40]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [41]:
mean_squared_error(y_test, test_predictions_ridge)

1.2607598873408044

In [42]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions_ridge))
RMSE

1.1228356457384154