In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns 


In [8]:
df= pd.read_csv('D:\Python\ML Live\Modular1\ML_Live-\data\Advertising.csv', index_col=0)
df

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [17]:
X = df.drop('Sales', axis = 1)
X

TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [19]:
y = df['Sales']
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: Sales, Length: 200, dtype: float64

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [27]:
poly_conv = PolynomialFeatures(degree= 3 , include_bias= False)   

In [28]:
final_model = LinearRegression()

In [56]:
poly_features = poly_conv.fit_transform(X)
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [63]:
X.to_numpy()[0]


array([230.1,  37.8,  69.2])

In [33]:
X.shape

(200, 3)

In [34]:
poly_features.shape

(200, 19)

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.33, random_state=101)


In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
scaler = StandardScaler()

In [64]:
scaled_X_train = scaler.fit_transform(X_train)

In [51]:
#scaled_X_train = scaler.transform(X_train)   

In [52]:
scaled_X_test = scaler.transform(X_test)

In [55]:
X_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [65]:
scaled_X_train[0]

array([ 0.455913  , -0.15469995, -0.98899258,  0.23144458,  0.12990319,
       -0.57856073, -0.43655678, -0.66806654, -0.71668198,  0.02389419,
        0.04869878, -0.45436665, -0.22089285, -0.47664217, -0.51504813,
       -0.55818067, -0.60618091, -0.56426029, -0.5063835 ])

In [54]:
scaled_X_test[0]

array([-0.88585021,  1.78850357,  0.75279488, -0.94268603,  0.04504514,
       -0.24391745,  2.35286478,  1.66213511,  0.43363357, -0.85817564,
       -0.5194069 , -0.51483477,  0.48397764,  0.26923803, -0.14681754,
        2.81970897,  2.22798415,  0.9755699 ,  0.14551054])

In [67]:
final_model.fit(X_train, y_train)

LinearRegression()

In [73]:
test_pred_scaled = final_model.predict(X_test)
test_pred_scaled

array([14.63372092, 19.05502371, 12.60912937, 17.2990722 ,  7.77663186,
        6.82526502, 19.96783499, 17.13494321, 10.38316136, 19.70400344,
        9.4100492 , 13.95881768, 11.61617522, 22.947182  , 18.90183411,
        9.42091718, 12.35426982,  9.41694192,  8.7613977 , 21.27645807,
        6.83781314, 19.30427609, 27.35825582, 24.30865659,  9.45328733,
       11.27279575, 20.73582968,  9.63134669, 12.525551  ,  8.43317338,
        8.79449102, 19.74446296, 10.90697498,  6.92971566, 18.07940374,
        9.45452183, 10.73111886,  9.92794975,  7.07720069, 10.74715111,
       12.15403331, 10.34977084, 11.58588333,  7.61811127, 11.90823723,
       10.76007269,  5.14855579, 15.27095102, 12.95416074, 22.40476607,
       10.72322437, 12.79300442, 14.91953663, 12.22762833, 11.13893795,
        4.91876287, 24.97394881,  9.48559677, 17.27334217, 15.54639358,
       15.02351556, 25.82928505,  8.73778123, 21.26133606, 11.96688674,
       21.76326629])

In [70]:
y_test

38     14.7
110    19.8
32     11.9
90     16.7
67      9.5
       ... 
184    26.2
128     8.8
54     21.2
101    11.7
94     22.2
Name: Sales, Length: 66, dtype: float64

In [74]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [77]:
mean_squared_error(y_test,test_pred_scaled)

0.3110577136477495

In [78]:
mean_absolute_error(y_test,test_pred_scaled)

0.393218528656395

In [79]:
np.sqrt(mean_squared_error(y_test,test_pred_scaled))

0.5577254823367401