In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns 


In [64]:
df= pd.read_csv('D:\Python\ML Live\Modular1\ML_Live-\data\Advertising.csv', index_col=0)
df

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [65]:
X=df.drop(['Sales'], axis = 1)
X

TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [66]:
y = df['Sales']
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: Sales, Length: 200, dtype: float64

## Polynomial Regression
### importing sklearn for poly features & Linear regression

In [67]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [68]:
poly_conv = PolynomialFeatures(degree=3 , include_bias=False)    # object poly_conv for class PolynomialFeatures

In [69]:
final_model = LinearRegression()     # object final_model for class LinearRegression

In [70]:
poly_features = poly_conv.fit_transform(X)     #fiting X data into poly_features. poly_features contains all the polynomial features

In [71]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.33, random_state=42)   #used poly_features as the X



### Scaling Data

In [73]:
from sklearn.preprocessing import StandardScaler  

In [74]:
scaler = StandardScaler()    #object scaler ofr class StandardScaler

In [75]:
scaler.fit(X_train)     #using object scaler to fit X_train, Z score

StandardScaler()

In [76]:
scaled_X_train = scaler.transform(X_train)    #stored all fitted X_train in scaled_X_train

In [77]:
scaled_X_test = scaler.transform(X_test)     #stored all fitted X_train in scaled_X_test

## RidegCV

In [78]:
from sklearn.linear_model import RidgeCV

In [79]:
ridge_cv_model = RidgeCV(alphas=(0.1,1,10), cv = 10, scoring='neg_mean_absolute_error')   # onject ridge_cv_model for class RidgeCV


In [80]:
from sklearn.metrics import SCORERS   # for all scoring techniques

In [81]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [82]:
ridge_cv_model.fit(scaled_X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10,
        scoring='neg_mean_absolute_error')

In [83]:
ridge_cv_model.alpha_   #best alpha hyperparameter

0.1

In [84]:
test_predictions_ridge = ridge_cv_model.predict(scaled_X_test)

In [85]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [86]:
MAE_Ridge = mean_absolute_error(y_test, test_predictions_ridge )
MAE_Ridge

0.43430757663863767

In [87]:
RMSE_Ridge = np.sqrt(mean_squared_error(y_test, test_predictions_ridge ))
RMSE_Ridge

0.5635899169466654

In [88]:
ridge_cv_model.coef_

array([ 5.84681185,  0.52142086,  0.71689997, -6.17948738,  3.75034058,
       -1.36283352, -0.08571128,  0.08322815, -0.34893776,  2.16952446,
       -0.47840838,  0.68527348,  0.63080799, -0.5950065 ,  0.61661989,
       -0.31335495,  0.36499629,  0.03328145, -0.13652471])

## LASSO

In [89]:
from sklearn.linear_model import LassoCV

In [90]:
lasso_cv_model = LassoCV(eps = 0.001, n_alphas = 200, cv=5, max_iter = 1000000)

In [91]:
lasso_cv_model.fit(scaled_X_train, y_train)

LassoCV(cv=5, max_iter=1000000, n_alphas=200)

In [92]:
lasso_cv_model.alpha_

0.004968802520343366

In [93]:
test_predictions_lasso = lasso_cv_model.predict(scaled_X_test)

In [94]:
RMSE_Lasso = np.sqrt(mean_squared_error(y_test, test_predictions_lasso))
RMSE_Lasso

0.5785146895301977

In [95]:
lasso_cv_model.coef_

array([ 5.19612354,  0.43037087,  0.29876351, -4.80417579,  3.46665205,
       -0.40507212,  0.        ,  0.        ,  0.        ,  1.35260206,
       -0.        ,  0.        ,  0.14879719, -0.        ,  0.        ,
        0.        ,  0.09649665,  0.        ,  0.04353956])

## ElasticNet

In [96]:
from sklearn.linear_model import ElasticNetCV

In [97]:
elastic_cv_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.99,1],eps = 0.001, n_alphas=100, max_iter=10000000 )

In [98]:
elastic_cv_model.fit(scaled_X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.99, 1], max_iter=10000000)

In [99]:
elastic_cv_model.alpha_

0.004968802520343366

In [100]:
test_predictions_elastic = elastic_cv_model.predict(scaled_X_test)

In [101]:
RMSE_Elastic = np.sqrt(mean_squared_error(y_test, test_predictions_elastic))
RMSE_Elastic

0.5785146895301977

In [102]:
elastic_cv_model.coef_

array([ 5.19612354,  0.43037087,  0.29876351, -4.80417579,  3.46665205,
       -0.40507212,  0.        ,  0.        ,  0.        ,  1.35260206,
       -0.        ,  0.        ,  0.14879719, -0.        ,  0.        ,
        0.        ,  0.09649665,  0.        ,  0.04353956])